articles/urls.py
from django.contrib import admin
from django.urls import path
from . import views


app_name = "articles"
urlpatterns = [
    path('', views.articles_list, name='list'),
    path('<slug>', views.article_detail, name='detail'),

]

securityBlog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('about/', views.about),
    path('contact', views.contact),
    path('articles/', include('articles.urls')),

]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articles/models.py
from django.db import models

# Create your models here.


class Article(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(default='default.jpg', blank=True)
    # Author

    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:50] + "..."

articles/views.py
from django.shortcuts import render, HttpResponse
from . import models

# Create your views here.


def articles_list(request):
    articles = models.Article.objects.all().order_by('-date')
    args = {'articles': articles}
    return render(request, 'articles/articleslist.html', args)


def article_detail(request, slug):
    article = models.Article.objects.get(slug=slug)
    return render(request, 'articles/article_detail.html', {'article': article})

securityBlog/views.py
from django.shortcuts import render, HttpResponse


def about(request):
    # return HttpResponse("Hello World!")
    return render(request, 'about.html')


def contact(request):
    # return HttpResponse("Hello my name is ali Trump")
    return render(request, 'contact.html')

articles/templates/articles/article_detail.html
{% extends 'base.html' %}

{% block content %}

<div class="article-detail">
    <div class="article">
        <img src="{{article.image.url}}" alt="">
        <h1>{{article.title}}</h1>
        <p>{{article.body}}</p>
        <p>{{article.date}}</p>
        <p>{{article.image}}</p>

    </div>
</div>

{% endblock %}

articles/templates/articles/articleslist.html
{% extends 'base.html' %}


{% block title %}
Articles
{% endblock %}

{% block content %}
<div class="container">
    <h1>Articles List</h1>
    {% for article in articles %}
        <h2><a href="{% url 'articles:detail' slug=article.slug %}">{{article.title}}</a></h2>
        <p>{{article.snippet}}</p>
        <p>{{article.date}}</p>
    {% endfor %}
</div>
{% endblock %}

templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>about page</title>
</head>
<body>
<h1>This is about page</h1>

</body>
</html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
    {% block title %}
    {% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'styles.css' %}">
</head>
<body>
        <h2><a href="{% url 'articles:list' %}">LOGO</a></h2>
        <div class="wrapper">
        {% block content %}

        {% endblock %}

        </div>

</body>
</html>

templates/contact.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>contact page</title>
</head>
<body>

<h1>This page is Contact with me</h1>
<p><strong>Tel:</strong>+989117450522</p>
<p><strong>Add:</strong>Iran, Mazandaran, Babol</p>

</body>
</html>